### ISSUE TITLE
prefer-jasmine-matcher rule bug

### ISSUE THREAD

**Issue by emilos** [tlvince/eslint-plugin-jasmine#136]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Linter throws an error for `expect` call expression with no arguments.

```
TypeError: Cannot read property 'type' of undefined
    at Linter.CallExpression (C:\projects\NG\node_modules\eslint-plugin-jasmine\lib\rules\prefer-jasmine-matcher.js:20:23)
    at emitOne (events.js:101:20)
    at Linter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (C:\projects\NG\node_modules\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (C:\projects\NG\node_modules\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (C:\projects\NG\node_modules\eslint\lib\util\node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (C:\projects\NG\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:602:23)
    at Traverser.enter (C:\projects\NG\node_modules\eslint\lib\linter.js:922:36)
    at Traverser.__execute (C:\projects\NG\node_modules\estraverse\estraverse.js:397:31)
    at Traverser.traverse (C:\projects\NG\node_modules\estraverse\estraverse.js:501:28)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Write any spec with `expect();` and make it run through eslint

```js
import Foo from "foo";

describe("foo", function () {
    it("is defined", function () {
        expect();
    });
});

```

**What is the expected behavior?**

No error, the call expression should be ignored or reported as an error such as `no-empty-expect`.

**Please mention your node.js, eslint-plugin-jasmine and operating system version.**

node 8

eslint-plugin-jasmine 2.7.1

ubuntu 16.04

I'll be happy to fix this next week, but maybe someone can pick it up sooner :)

**Comment by DianaSuvorova** [comment]
yeah, this is a bug. Thanks for reporting! I should be able to look at this later today.
