### ISSUE TITLE
Getting Error: ESLint: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by JaySeeAre** [tlvince/eslint-plugin-jasmine#156]
**Do you want to request a *feature* or report a *bug*?**
*Bug*
**What is the current behavior?**
Intermitently while editing tests in VSCode I am getting an error:  
`ESLint: Cannot read property 'body' of undefined. Please see the 'ESLint' output channel for details.`
In the output channel I have:
```
[Error - 16:28:30] ESLint stack trace:
[Error - 16:28:30] TypeError: Cannot read property 'body' of undefined
    at getDescribeDeclarationsContent (c:\Src\Repos\html5-training\server\node_modules\eslint-plugin-jasmine\lib\rules\new-line-between-declarations.js:46:80)
    at CallExpression (c:\Src\Repos\html5-training\server\node_modules\eslint-plugin-jasmine\lib\rules\new-line-between-declarations.js:17:28)
    at listeners.(anonymous function).forEach.listener (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (c:\Src\Repos\html5-training\server\node_modules\eslint\lib\linter.js:1006:32)
```
It looks like there is just an extra check that is required on line 46 of `new-line-between-declarations.js`:
```
if (describe.arguments && describe.arguments[1] && describe.arguments[1].body.body) {
  ...
}
```
should be:
```
if (describe.arguments && describe.arguments[1] && describe.arguments[1].body && describe.arguments[1].body.body) {
  ...
}
```
I could raise a PR if you would accept it?

**If the current behavior is a bug, please provide the steps to reproduce.**
Setup ESLint in VsCode, with the jasmine plugin and create some tests. Every now and then you will get this error.

It seems to occur when creating a describe immediately after another:
```
describe("some behaviour", function() {
  ...
});
describe("", function);
```
when you get to this point in writing the second describe, VSCode reports the error. presumably becasue there is no body on the second function yet...

**What is the expected behavior?**
I wouldn't expect to ESlint to recieve an exception.

**Please mention your node.js, eslint-plugin-jasmine and operating system version.**
Node: v8.9.4
ESLint-Plugin-Jasmine: v2.9.1
VSCode: 1.20.1
OS: Windows 10

**Comment by burabure** [comment]
thanks for debugging this! a PR would be awesome!
