### ISSUE TITLE
named-spy throws if spy is chained

### ISSUE THREAD

**Issue by SimenB** [tlvince/eslint-plugin-jasmine#49]
``` js
const getStateMock = jasmine.createSpy('getState').and.returnValue(stateMock)
```

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.CallExpression (/home/testyo/repos/frontend-repo/code/node_modules/eslint-plugin-jasmine/lib/rules/named-spy.js:31:56)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/testyo/repos/frontend-repo/code/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/home/testyo/repos/frontend-repo/code/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/testyo/repos/frontend-repo/code/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.module.exports.api.verify.traverser.traverse.enter (/home/testyo/repos/frontend-repo/code/node_modules/eslint/lib/eslint.js:869:36)
    at Controller.__execute (/home/testyo/repos/frontend-repo/code/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/testyo/repos/frontend-repo/code/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.controller.traverse (/home/testyo/repos/frontend-repo/code/node_modules/eslint/lib/util/traverser.js:38:33)
```

cc @remcohaszing

**Comment by burabure** [comment]
@SimenB I couldn't reproduce with the current version. I think this is probably solved
